### ISSUE TITLE
App crashes if there is database incosistency 

### ISSUE THREAD

**Issue by konishon** [fieldsight/fieldsight-mobile#1]
#### Problem description
App crashes on load if there is any inconsistency in room database

#### Steps to reproduce the problem
Install the latest version from playstore
Login and sync everything
Uninstall the app
Install a older version (https://mega.nz/#!XihmTAyZ!WU8sxi4CRU9y7jKcoLUOrwQaJTg6SxaZeLjiRJFJNsk)

#### Expected behavior
The app should show there is a inconsistency in database and prompt to reset database if there is not critical files such as offline sites or filled submission

**Comment by nishontan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Room db crash](https://trello.com/c/dWPjfIHU/297-room-db-crash)

**Comment by konishon** [comment]
```
@Database(entities =
        {
                Site.class,
                Project.class,
                SyncableItem.class,
                GeneralForm.class,
                ScheduleForm.class,
                Stage.class,
                SubStage.class,
                SurveyForm.class,
                SiteType.class,
                SiteRegion.class,
                FieldSightNotification.class,
                Em.class,
                FieldSightContactModel.class,
                SubmissionDetail.class

        },
        version = 7)
```

I downgraded to 7 in `FieldSightDatabase.java`

and still got ```: java.lang.IllegalStateException: A migration from 8 to 7 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...)```

**Comment by hereyubaraj** [comment]
This issues is no more relevant.
