### ISSUE TITLE
A site appears under general forms.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#111]
Sometimes randomly a site named Nishon appears inside the general form list.
![nishon site displayed automatically (1)](https://user-images.githubusercontent.com/20319653/56416264-0f2ec400-62b0-11e9-8b81-2c2a943f19b5.png)

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ['Nishon' site appearing occasionally in mobile app when synced](https://trello.com/c/WKeXE9LT/472-nishon-site-appearing-occasionally-in-mobile-app-when-synced)

**Comment by konishon** [comment]
Closed by #372
