### ISSUE TITLE
Submission mismatch

### ISSUE THREAD

**Issue by awemulya** [fieldsight/fieldsight-mobile#14]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by awemulya** [comment]
https://github.com/fieldsight/fieldsight/issues/36

**Comment by konishon** [comment]
This has been fixed and merged #9
https://trello.com/c/jYIg60gW/293-different-forms-uploading-to-a-single-same-form
