### ISSUE TITLE
Code refractor

### ISSUE THREAD

**Issue by hereyubaraj** [fieldsight/fieldsight-mobile#174]

**Comment by yubarajpoudel** [comment]
[Trello link ](https://trello.com/c/crTYayiD/744-code-refractoring)

**Comment by yubarajpoudel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Code refractoring](https://trello.com/c/crTYayiD/744-code-refractoring)

**Comment by yubarajpoudel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Code refractoring](https://trello.com/c/crTYayiD/744-code-refractoring)

**Comment by yubarajpoudel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Code refractoring](https://trello.com/c/crTYayiD/744-code-refractoring)
