### ISSUE TITLE
Form Sync - After Form syncing, general forms are not displayed in the mobile app, might not have been downloaded.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#185]
But all other staged, survey and scheduled forms are displayed in their respected projects and/or sites.
Mobile's fieldsight folder attached for reference.
[fieldsight_compressed.zip](https://github.com/fieldsight/fieldsight-mobile/files/3245783/fieldsight_compressed.zip)

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Form Sync - After Form syncing, general forms are not displayed in the mobile app, might not have been downloaded.](https://trello.com/c/v5OpXQeF/632-form-sync-after-form-syncing-general-forms-are-not-displayed-in-the-mobile-app-might-not-have-been-downloaded)

**Comment by santoshkhatrii** [comment]
@hereyubaraj 
@nishontan 
 **Steps to replicate issue:**

1. Download a project's data
2. Go to that project. The forms are displayed.
3. Go to project list and visit another project.
4. View the forms inside that another project.
5. Go back to the first project in step 2.
6. The forms inside the project disappear at this point, but have already been downloaded.

**Comment by santoshkhatrii** [comment]
Now this issue appeared in staged forms.

**Comment by konishon** [comment]
Fixed on #247
