### ISSUE TITLE
Series of problems in form because of two different forms with the same form ID and version.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#187]
While sending a form after filling it up, an error occured shown through toastr message shown as below: 
![Screenshot_20190603-102933_Fieldsight](https://user-images.githubusercontent.com/20319653/58776914-f40fdd80-85eb-11e9-85f9-321db3749d22.jpg)
This particular form could not be finalized, maybe because of the same reason. While trying to edit this form from saved form, the following error occured:
![Screenshot_20190603-103404_Fieldsight](https://user-images.githubusercontent.com/20319653/58777040-19045080-85ec-11e9-924a-2766a3a32795.jpg)
Attached db file from the mobile for reference:

[fieldsight_compressed.zip](https://github.com/fieldsight/fieldsight-mobile/files/3245911/fieldsight_compressed.zip)

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Mobile] Series of problems in form because of two different forms with the same form ID and version.](https://trello.com/c/ROqEM0Ti/634-mobile-series-of-problems-in-form-because-of-two-different-forms-with-the-same-form-id-and-version)

**Comment by konishon** [comment]
Closing as it could not be reproduced
