### ISSUE TITLE
Tapping 'Check Now' inside 'General/Staged/Scheduled Forms' takes to old Sync menu.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#195]
When there are no forms under the categories - general, scheduled or staged forms, or the forms are un-synced, then a text link appears that says `Check Now` (Screenshot 1).
Clicking that link takes to old sync screen (Screenshot 2) instead of the new one.

![Screenshot 1](https://user-images.githubusercontent.com/20319653/58791733-76ab9380-8612-11e9-8ae8-5c86d226a929.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/20319653/58791770-8925cd00-8612-11e9-814f-b1fd4ad02c49.jpg)

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Mobile] Tapping 'Check Now' inside 'General/Staged/Scheduled Forms' takes to old Sync menu.](https://trello.com/c/aNYmoYXY/642-mobile-tapping-check-now-inside-general-staged-scheduled-forms-takes-to-old-sync-menu)

**Comment by konishon** [comment]
I am just going to hide the button right now, we need to discuss and maybe remove them while we 
address #198 

@hereyubaraj what do you think?

**Comment by konishon** [comment]
Closed by
