### ISSUE TITLE
Save Form : Asking dialog even if form is saved and back pressed is clicked 

### ISSUE THREAD

**Issue by hereyubaraj** [fieldsight/fieldsight-mobile#23]
Before quitting form i saved the form but still shows the dialog even the form is saved successfully and back pressed.

![screenshot-1550564350457](https://user-images.githubusercontent.com/47551530/53000005-61d63600-344f-11e9-97f0-c5770a7bfc25.jpg)

**Comment by yubarajpoudel** [comment]
Not relevant anymore
