### ISSUE TITLE
Notifications - both push and from notification bell icon, are not being displayed. v2.8.11

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#230]
Flagging, approving, rejecting form notifications aren't displayed.

There are tons of notifications from the web, but displays 'Nothing here' in the notification page.

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications - both push and from notification bell icon, are not being displayed. v2.8.11](https://trello.com/c/PYlvVpCV/663-notifications-both-push-and-from-notification-bell-icon-are-not-being-displayed-v2811)

**Comment by hereyubaraj** [comment]
@santoshkhatrii in the released version, Notification are only saved at the time of recieved. Notification api are called in new-design `v3`.

**Comment by hereyubaraj** [comment]
We use to save notification when it is received. So it is supposed to show the list of received notification only.

**Comment by santoshkhatrii** [comment]
@hereyubaraj 
Does this means user will be devoid of all sorts of notifications until another version of the app with `notifications api v3` is published? Because no push notifications are received, and as mentioned, only *received notifications* are to be shown in *list of notification*, which is zero.
____
Then this should probably be included in the release note, stating that this feature is not working.
