### ISSUE TITLE
Old Sync UI when 'Resolve' button is clicked that appears when new form has been deployed from the web.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#257]
When new form is deployed to a project/site from the web, a pop-up like notification appears in the app if being used, that includes a button 'Resolve' as shown in [this screenshot](https://user-images.githubusercontent.com/20319653/60411961-febf9180-9bee-11e9-8a5f-0df0ecb4e181.jpg).
Tapping the 'Resolve' button takes to the old sync UI shown [here](https://user-images.githubusercontent.com/20319653/60412045-67a70980-9bef-11e9-809a-bc0956a9f0c9.jpg).

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Mobile] Old Sync UI when 'Resolve' button is clicked that appears when new form has been deployed from the web.](https://trello.com/c/l3QSn9H1/675-mobile-old-sync-ui-when-resolve-button-is-clicked-that-appears-when-new-form-has-been-deployed-from-the-web)

**Comment by konishon** [comment]
24da35a1961e2951dc39ffbb438775e389cd00ab Closes this
