### ISSUE TITLE
Terms and Labels missing at some instances.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#267]
Terms and Labels as set in web are not being displayed at some points in the mobile app.

Highlighted in screenshots below:
![Screenshot_20190709-150155_Fieldsight](https://user-images.githubusercontent.com/20319653/60876042-d53fdf00-a25a-11e9-82be-bcab1ed6ae25.jpg)
![Screenshot_20190709-150211_Fieldsight](https://user-images.githubusercontent.com/20319653/60876045-d5d87580-a25a-11e9-81bf-9082a827b994.jpg)
![Screenshot_20190709-150241_Fieldsight](https://user-images.githubusercontent.com/20319653/60876046-d5d87580-a25a-11e9-9b6b-e27ea22ecd32.jpg)

**Comment by yubarajpoudel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Mobile] Terms and Labels missing at some instances.](https://trello.com/c/gu9Kbgu9/695-mobile-terms-and-labels-missing-at-some-instances)
