### ISSUE TITLE
Submission Upload Error - Host Name may not be null.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#279]
#### Software and hardware versions 
Collect v3.0.6, Android v9.0, device used - Samsung Galaxy S9

#### Problem description
Failed to submit form from mobile app.

#### Steps to reproduce the problem
- Submit a filled form the mobile app.
- Flag the submission from the web. Notification appears on the mobile app.
- Tap the notification and edit the flagged form. Submit this form again.
- While submitting the form, this error appears.
![Screenshot_20190712-104954_Fieldsight](https://user-images.githubusercontent.com/20319653/61103872-9cd71580-a493-11e9-8dfc-b7f2aa6c8469.jpg)

#### Expected behavior
The form should be submitted successfully.

#### Other information 
Deleting the saved form, and filling the form again works.

**Comment by santoshkhatrii** [comment]
One highly likely reason for this issue could be treating flagged submission that is submitted again as the original submission. The submission id doesn't change now no matter how many times we submit the flagged submission. That could be also the reason behind working of the submission process after the saved forms are deleted.

**Comment by yubarajpoudel** [comment]
@santoshkhatrii not found this currently
