### ISSUE TITLE
Could not register dialog always pops up 

### ISSUE THREAD

**Issue by konishon** [fieldsight/fieldsight-mobile#3]
#### Software and hardware versions 
Collect v2.5.1, Android 8.1

#### Problem description
Could not register dialog always pops up when trying to login for the first time 
but user can login when trying for the second time
![screenshot_1548139802](https://user-images.githubusercontent.com/11831955/51517226-378a5c00-1e42-11e9-8363-69765cc29b5c.png)

#### Steps to reproduce the problem
Enter username / password
Press login

#### Expected behavior
Should login on the first try

**Comment by konishon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Could not register dialog always pops up #3](https://trello.com/c/TfoEGH3z/203-could-not-register-dialog-always-pops-up-3)

**Comment by nishontan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Could not register dialog always pops up #3](https://trello.com/c/TfoEGH3z/203-could-not-register-dialog-always-pops-up-3)

**Comment by konishon** [comment]
00b598f closes this
