### ISSUE TITLE
Open form from notification: Back button doesn't work when the form is opened.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#35]
#### Software and hardware versions 
Collect v5.6.0, Android v7.1

#### Problem description
Back button is not working

#### Steps to reproduce the problem
1. For any flagged/approved/rejected form, click the notification. You'll be redirected to the notification page.
2. Click on this particular notification, for the form that was flagged/approved/rejected. You'll reach in the following page.
![screen shot 2019-02-22 at 11 37 23 am](https://user-images.githubusercontent.com/20319653/53222548-46a93780-3696-11e9-9251-21cb85f22b68.png)
3. Click on the Form name (in this case the form name is Test Picture)
4. The form opens (if already available, it opens the local copy, if not, it downloads the form and opens)
5. This highlighted back button (in the following screenshot) doesn't work
![screen shot 2019-02-22 at 11 39 10 am](https://user-images.githubusercontent.com/20319653/53222622-87a14c00-3696-11e9-8e38-11baf07f98d4.png)

#### Expected behavior
Should take the user to the previous screen.

**Comment by konishon** [comment]
@santoshkhatrii Thanks for the detailed issue
