### ISSUE TITLE
'Next' button is disabled in the form after following these following steps.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight-mobile#402]
Steps
----
1. Check for a flagged submission that appears in the notification.
2. Click the notification to open the form.
3. Click on 'Go to last/end' in the bottom right corner.

OR, Instead of following steps 1, 2 and 3, Click on the Arrow icon beside save icon in the top right in any form filling page, then click on 'Go to last/end' button in the bottom right.
Then proceed below:
 
4. Click on 'Previous' in the bottom left corner.
_____
Now the 'Next' button in the bottom right is disabled no matter which page we are in the form.

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MOBILE] 'Next' button is disabled in the form after following these following steps.](https://trello.com/c/8DlzvLfg/1020-mobile-next-button-is-disabled-in-the-form-after-following-these-following-steps)

**Comment by yubarajpoudel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [next button disabled issue](https://trello.com/c/iEXf6kCk/1036-next-button-disabled-issue)
